


# PostgreSQL
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
# Your app name(e.g. my app directory folder name is fotoset-backend)
  database: titan_development_db
# you need to put your username and password here
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
test:
  <<: *default
# Your app name(e.g. my app directory folder name is fotoset-backend)
  database: titan_test_db

production:
  <<: *default
# Your app name(e.g. my app directory folder name is fotoset-backend)
# you don’t need username and password here below
  database: titan_production
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>